import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/ResponsePage")
public class ResponsePage extends HttpServlet {
    protected void doPost(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
        res.setContentType("text/html");
        PrintWriter pw = res.getWriter();
        String companyName = req.getParameter("cname");
        String[] services = req.getParameterValues("cneed");
        String nPeople = req.getParameter("cpeople");
        pw.println("<html>");
        pw.println("<head><title>Response Page</title></head>");
        pw.println("<body>");
        pw.println("<div style=\"border: 2px solid black;\">");
        pw.println("<h1>Example Form Response</h1>");
        pw.println("<p style=\"color: green;\">This page was generated by a servlet</p>");
        pw.println("<p> The query string is <br> </p>");
        pw.println("<p>company name = " + companyName + "</p>");
        pw.println("<p>The values of the parameters sent by the form are</p>");
        pw.println("<p>number of people: " + nPeople + "</p>");
        pw.println("<p>company name: " + companyName + "</p>");
        pw.println("<p>hosting : " + services[0] + "</p>");
        pw.println("<p>design : " + services[1] + "</p>");
        pw.println("<p>javadev : " + services[2] + "</p>");
        pw.println(
                "<h2 style=\"color: rgb(243, 37, 209);\">We would love to help your large company to solve its needs for </h2>");
        pw.println("<ul style=\"color: rgb(243, 37, 209);\">");
        for (String service : services) {
            pw.println("<li>" + service + "</li>");
        }
        pw.println("</ul>");
        pw.println("</div>");
        pw.println("</body>");
        pw.println("</html>");
    }
}
